# Generated by Django 4.0.3 on 2022-03-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_listing_watchlist_listings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='url',
        ),
        migrations.AddField(
            model_name='listings',
            name='image',
            field=models.ImageField(blank=True, upload_to='listing_images/'),
        ),
    ]
